spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recipeapp
    username: root
    password: mieiuminho
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true